# Generated by Django 5.0.3 on 2024-07-30 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homesite', '0003_remove_order_price_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='for_men',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='for_women',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
